name: 04 with report generation
on: push

jobs:
  tests:
    name: Run and upload report
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache mvn packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}            

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'

      - name: maven build
        run: mvn clean install

      - name: start playwright browser
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chromium"

      - name: Run Tests via Maven
        run: mvn test surefire-report:report


      - name: Upload Test Reports  # Uploads test results as artifacts for later review.
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts  # The artifact name displayed in GitHub Actions.
          path: |
            target/reports
            target/surefire-reports


      - name: Publish Test report  # Displays the Surefire test report in the GitHub Actions UI.
        uses: phoenix-actions/test-reporting@v15
        with:
          name: 'Publish surefire report'  # The title of the report in the summary.
          path: target/surefire-reports/TEST*.xml  # Specifies the test results file(s).
          reporter: java-junit  # Specifies the report format.
          list-tests: all  # Displays details of all tests in the summary.
          list-suites: all  # Displays test suite details.
          fail-on-error: true  # Fails the workflow if the report contains errors.
          output-to: 'step-summary'  # Displays the report in the GitHub Actions summary tab.
